name: state_man_examples
description: Demo app for experimenting with state management approaches.

version: 0.0.1

environment:
  sdk: ">=2.15.1 <3.0.0"

dependencies:
  cupertino_icons: ^1.0.2
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  lint: 1.8.2

# The following section is specific to Flutter.
flutter:
  uses-material-design: true
